WolkenMusic/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from music import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('music.urls')),
    url(r'^songs/(?P<pk>[0-9]+)/update/$', views.UpdateSong.as_view(), name="song_update"),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^play/(?P<song_id>[0-9]+)/$', views.playindex, name='playindex'),
    url(r'^next/$', views.nextindex, name='nextindex'),
    url(r'^prev/$', views.previndex, name='previndex'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<song_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/$', views.songs, name='songs'),
    url(r'^create_album/$', views.create_album, name='create_album'),
    url(r'^(?P<album_id>[0-9]+)/create_song/$', views.create_song, name='create_song'),
    url(r'^(?P<album_id>[0-9]+)/delete_song/(?P<song_id>[0-9]+)/$', views.delete_song, name='delete_song'),
    url(r'^(?P<album_id>[0-9]+)/favorite_album/$', views.favorite_album, name='favorite_album'),
    url(r'^(?P<album_id>[0-9]+)/delete_album/$', views.delete_album, name='delete_album'),
    url(r'^(?P<album_id>[0-9]+)/play/(?P<song_id>[0-9]+)/$', views.playalbum, name='playAlbum'),
    url(r'^(?P<album_id>[0-9]+)/next/$', views.nextalbum, name='nextAlbum'),
    url(r'^(?P<album_id>[0-9]+)/prev/$', views.prevalbum, name='prevAlbum'),
    url(r'album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name="album_update"),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/play/(?P<song_id>[0-9]+)/$', views.playsongs, name='playsong'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/next/$', views.nextsongs, name='nextsong'),
    url(r'^songs/(?P<filter_by>[a-zA_Z]+)/prev/$', views.prevsongs, name='prevsong'),
    url(r'^updateprofile/$', views.UpdateProfile.as_view(), name='update_profile'),
    url(r'^create_playlist/$',views.create_playlist,name='create_playlist'),
    url(r'^playlists/(?P<filter_by>[a-zA_Z]+)/$', views.playlists, name='playlists'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/favorite/$', views.favorite_playlist, name='favorite_playlist'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/delete/$', views.delete_playlist, name='delete_playlist'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/songs/(?P<filter_by>[a-zA_Z]+)/$', views.playlist_songs,
        name='playlist_songs'),
    url(r'^playlists/(?P<song_id>[0-9]+)/addsong/$', views.add_to_song, name='add_to_playlist'),
    url(r'^playlists/(?P<song_id>[0-9]+)/removesong/$', views.remove_playlist_song, name='remove_song'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/songs/(?P<filter_by>[a-zA_Z]+)/play/(?P<song_id>[0-9]+)/$',
        views.playplaylist, name='playplaylist'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/songs/(?P<filter_by>[a-zA_Z]+)/next$',
        views.nextplaylist, name='nextplaylist'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/songs/(?P<filter_by>[a-zA_Z]+)/prev/$',
        views.prevplaylist, name='prevplaylist'),
    url(r'^playlists/(?P<playlist_id>[0-9]+)/share/$', views.share_playlist, name='share_playlist'),
    url(r'^sharedplaylist/(?P<filter_by>[a-zA_Z]+)/$', views.shared_playlist, name='shared_playlist'),
    url(r'^sharedplaylist/(?P<playlist_id>[0-9]+)/(?P<user_id>[0-9]+)/(?P<filter_by>[a-zA_Z]+)/delete/$',
        views.delete_shared_playlist, name='delete_shared'),
]

music/models.py
from django.contrib.auth.models import User
from django.db import models


class Album(models.Model):
    GENRE_TYPE =(("Pop", "Pop"), ("Rock", "Rock"), ("Classical", "Classical"), ("Folk", "Folk"), ("Unknown", "Unknown"))
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100,choices=GENRE_TYPE)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=250)
    audio_file = models.FileField(default='')
    played_counter = models.IntegerField(default=0)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title


class Playlist(models.Model):
    playlist_name = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return self.playlist_name


class PlaylistInfo(models.Model):
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    song = models.ForeignKey(Song)


class SharedPlaylist(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner')
    shared = models.ForeignKey(User, on_delete=models.CASCADE, related_name='shared')
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)

music/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Album, Song, PlaylistInfo, Playlist, SharedPlaylist


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):

    class Meta:
        model = Song
        fields = ['audio_file']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        # first call parent's constructor
        super(UserForm, self).__init__(*args, **kwargs)
        # there's a `fields` property now
        self.fields['password'].required = True
        self.fields['username'].required = True
        self.fields['email'].required = True

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class PlaylistInfoForm(forms.ModelForm):

    class Meta:
        model = PlaylistInfo
        fields = ['playlist']


class PlaylistForm(forms.ModelForm):

    class Meta:
        model = Playlist
        fields = ['playlist_name']


class SharedPlaylistForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(SharedPlaylistForm, self).__init__(*args, **kwargs)
        self.fields['shared'].queryset = self.fields['shared'].queryset.exclude(id=user.id)

    class Meta:
        model = SharedPlaylist
        fields = ['shared']

music/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Sum
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.core.urlresolvers import reverse_lazy
from .forms import AlbumForm, SongForm, UserForm, PlaylistInfoForm , PlaylistForm, SharedPlaylistForm
from .models import Album, Song, Playlist, PlaylistInfo, SharedPlaylist
from mutagen.id3 import ID3
import os.path
from django.contrib import admin

PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

counter = 0
counters = 0
counterp = 0
counteri = 0


def create_album(request):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = AlbumForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            file_type = album.album_logo.url.split('.')[-1]
            file_type = file_type.lower()
            if file_type not in IMAGE_FILE_TYPES:
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'Image file must be PNG, JPG, or JPEG',
                }
                return render(request, 'music/create_album.html', context)
            album.save()
            return render(request, 'music/detail.html', {'album': album})
        context = {
            "form": form,
        }
        return render(request, 'music/create_album.html', context)


def create_song(request, album_id):
    form = SongForm(request.POST or None, request.FILES or None)
    album = get_object_or_404(Album, pk=album_id)
    if form.is_valid():
        albums_songs = album.song_set.all()
        for s in albums_songs:
            if s.song_title == form.cleaned_data.get("song_title"):
                context = {
                    'album': album,
                    'form': form,
                    'error_message': 'You already added that song',
                }
                return render(request, 'music/create_song.html', context)
        song = form.save(commit=False)
        song.album = album
        song.audio_file = request.FILES['audio_file']
        file_type = song.audio_file.url.split('.')[-1]
        file_type = file_type.lower()
        if file_type not in AUDIO_FILE_TYPES:
            context = {
                'album': album,
                'form': form,
                'error_message': 'Audio file must be WAV, MP3, or OGG',
            }
            return render(request, 'music/create_song.html', context)
        try:
            audio = ID3(song.audio_file)
            if 'TIT2' in audio:
                song.song_title = audio['TIT2'].text[0]
            else:
                song.song_title = song.audio_file
        except Exception:
            song.song_title = song.audio_file
        song.save()
        return render(request, 'music/detail.html', {'album': album})
    context = {
        'album': album,
        'form': form,
    }
    return render(request, 'music/create_song.html', context)


def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id)
    album.delete()
    albums = Album.objects.filter(user=request.user)
    return render(request, 'music/index.html', {'albums': albums})


def delete_song(request, album_id, song_id):
    album = get_object_or_404(Album, pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request, 'music/detail.html', {'album': album})


def delete_playlist(requset, playlist_id):
    playlist = get_object_or_404(Playlist,pk=playlist_id)
    playlist.delete()
    return render(requset, 'music/playlist.html', {'filter_by': 'all'})


def detail(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album, pk=album_id)
        song_list = []
        for s in album.song_set.all():
            song_list.append(s)
        return render(request, 'music/detail.html', {'album': album, 'user': user, 'song_list': song_list})


def playalbum(request, album_id, song_id):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album,pk=album_id)
        global counter
        counter = int(song_id);
        song_list = []
        for s in album.song_set.all():
            song_list.append(s)
        song = song_list[counter]
        temp_counter = song.played_counter
        temp_counter += 1
        song.played_counter = temp_counter
        song.save()
        return render(request, 'music/detail.html', {'album': album, 'user': user, 'song_list': song_list, 'curSong': song})


def playsongs(request, filter_by, song_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
            global counters
            counters = int(song_id)
            song = users_songs[counters]
            temp_counter = song.played_counter
            temp_counter += 1
            song.played_counter = temp_counter
            song.save()

        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
            'curSong': song
        })


def nextsongs(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
            global counters
            if counters < len(users_songs) - 1:
                counters += 1
                song = users_songs[counters]
                temp_counter = song.played_counter
                temp_counter += 1
                song.played_counter = temp_counter
                song.save()
            elif counters == len(users_songs) - 1:
                counters += 1
                song = None
            else:
                song = None

        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,
            'filter_by': filter_by,
            'curSong': song
        })


def nextalbum(request, album_id):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album,pk=album_id)
        global counter
        song_list = []
        for s in album.song_set.all():
            song_list.append(s)
        if counter < len(song_list)-1:
            counter += 1
            song = song_list[counter]
            temp_counter = song.played_counter
            temp_counter += 1
            song.played_counter = temp_counter
            song.save()
        elif counter == len(song_list)-1:
            counter += 1
            song = None
        else:
            song = None
        return render(request, 'music/detail.html', {'album': album, 'user': user, 'song_list': song_list, 'curSong': song})


def prevalbum(request, album_id):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        user = request.user
        album = get_object_or_404(Album,pk=album_id)
        global counter
        song_list = []
        for s in album.song_set.all():
            song_list.append(s)
        if counter > 0:
            counter -= 1
        elif counter <= 0:
            counter = 0
        song = song_list[counter]
        temp_counter = song.played_counter
        temp_counter += 1
        song.played_counter = temp_counter
        song.save()
        return render(request, 'music/detail.html', {'album': album, 'user': user, 'song_list': song_list, 'curSong': song})


def prevsongs(request, filter_by):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        try:
            song_ids = []
            for album in Album.objects.filter(user=request.user):
                for song in album.song_set.all():
                    song_ids.append(song.pk)
            users_songs = Song.objects.filter(pk__in=song_ids)
            if filter_by == 'favorites':
                users_songs = users_songs.filter(is_favorite=True)
            global counters
            if counters > 0:
                counters -= 1
            elif counters <= 0:
                counters = 0
            song = users_songs[counters]
            temp_counter = song.played_counter
            temp_counter += 1
            song.played_counter = temp_counter
            song.save()
        except Album.DoesNotExist:
            users_songs = []
        return render(request, 'music/songs.html', {
            'song_list': users_songs,

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Wolken Music{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>

    <script src="{% static 'music/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">WM</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block albums_active %}{% endblock %}"><a href="{% url 'music:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'music:songs' 'all' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs</a></li>
                <li class="{% block playlist_active %}{% endblock %}"><a href="{% url 'music:playlists' 'all' %}"><span class="glyphicon glyphicon-headphones" aria-hidden="true"></span>&nbsp; Playlist</a></li>
                <li class="{% block sharedplaylist_active %}{% endblock %}"><a href="{% url 'music:shared_playlist' 'shared' %}"><span class="glyphicon glyphicon-link" aria-hidden="true"></span>&nbsp; Shared Playlist</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'music:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:create_album' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:update_profile' %}">
                        <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Profile
                    </a>
                </li>
                <li>
                    <a href="{% url 'music:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/create_playlist.html
{% extends 'music/base.html' %}
{% block title %}Add a New Playlist{% endblock %}
{% block body %}

<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add Playlist</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                   <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/playlist.html
{% extends 'music/base.html' %}
{% block title %}Playlist{% endblock %}
{% block playlist_active %}active{% endblock %}
{% block body %}
{% if message %}
    message
{% endif %}

    <div class="col-sm-12">
        <a href="{% url 'music:create_playlist' %}">
            <button style="float:right;" type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add New Playlist
            </button>
        </a>
    </div>
    <div class="container-fluid songs-container">
    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:playlists' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:playlists' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    {% if playlist_list %}
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Playlist Name</th>
                                <th>Favorite</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for playlist in playlist_list %}
                                <tr>
                                    <td><a href="{% url 'music:playlist_songs' playlist.id 'all' %}">{{ playlist.playlist_name }}</a></td>
                                    <td>
                                        <a href="{% url 'music:favorite_playlist' playlist.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if playlist.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                    <td>
                                        <form action="{% url 'music:delete_playlist' playlist.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                            <input type="hidden" name="playlist_id" value="{{ playlist.id }}" />
                                            <button type="submit" class="btn btn-danger btn-xs">
                                                <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                            </button>
                                        </form>
                                        <form action="{% url 'music:share_playlist' playlist.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                            <input type="hidden" name="playlist_id" value="{{ playlist.id }}" />
                                            <button type="submit" class="btn-success btn-xs">
                                                <span class="glyphicon glyphicon-share"></span>&nbsp; Share
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                            {% endfor %}

                        </tbody>
                    </table>
                    {% else %}
                        No Playlist To Show !
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/songs.html
{% extends 'music/base.html' %}
{% block title %}All Songs{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
    {%if curSong %}
    <script>
    window.onload = function(){
        var url  = '{{ curSong.audio_file.url }}';
        var audio = document.getElementById('audio');
        var source = document.getElementById('asource');
        var sname = document.getElementById('player_sname');
        var aname = document.getElementById('player_aname');
        sname.innerText='{{ curSong.song_title }}';
        aname.innerText='Album: '+'{{ curSong.album.album_title }}';
        source.src = url;
        audio.load();
        audio.play();
    }
    </script>
    {% endif %}
    <div class="container-fluid songs-container">

    <div class="row">
        <div class="col-sm-12">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" {% if filter_by == 'all' %}class="active"{% endif %}><a href="{% url 'music:songs' 'all' %}">View All</a></li>
                <li role="presentation" {% if filter_by == 'favorites' %}class="active"{% endif %}><a href="{% url 'music:songs' 'favorites' %}">Favorites</a></li>
            </ul>
        </div>
    </div>

    <div class="row">

        <div class="col-sm-12">

            <div class="panel panel-default">
                <div class="panel-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Song Title</th>
                                <th>Artist</th>
                                <th>Audio File</th>
                                <th>Album</th>
                                <th>Favorite</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for song in song_list %}
                                <tr>
                                    <td>{{ song.song_title }}</td>
                                    <td>{{ song.album.artist }}</td>
                                    <td>
                                        <a href="{% url 'music:playsong' filter_by forloop.counter0 %}">
                                            <button type="button" class="btn btn-success btn-xs" onclick="set_source('{{ song.audio_file.url }}')">
                                                <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                            </button>
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:detail' song.album.id %}">
                                            <img src="{{ song.album.album_logo.url }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                        </a>
                                        <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                    </td>
                                    <td>
                                        <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                    </td>
                                    <td>
                                        <form action="{% url 'music:add_to_playlist' song.id %}" method="GET" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-info btn-xs">
                                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Add To Playlist
                                        </button></form>
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

    </div>
        {% if curSong %}
    <div id="player" style="background:#FFFFF;border-bottom:3px solid #dfd4ce;border-top: 3px solid #dfd4ce;padding:0 5%;position:fixed;bottom:0;width:100%;">
           <a href="{% url 'music:prevsong' filter_by %}">
            <button type="button">Previous</button>
        </a>
        <audio id="audio" controls="controls" style="margin:10px">
            <source id="asource" src=""/>
            Your Browser Does Not Support the audio format
        </audio>
         <a href="{% url 'music:nextsong' filter_by %}">
            <button type="button" onclick="">Next</button>
        </a>
         </a><div id="player_sname"></div>
        <div id="player_aname"></div>
    </div>
        {% endif %}
</div>
{% endblock %}